name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --release
      env:
        DATA_POST_URL: http://localhost:8000/core/rapid-scan-data/
